name: docker-image-push-public-dash

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get-branch-name.outputs.branch_name }}
    steps:
      - name: Get branch name based on ref_type
        id: get-branch-name
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            target_branch=${{ github.event.release.target_commitish }}
            echo "branch_name=${target_branch}" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_type }}" == "branch" ]; then
            echo "branch_name=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"    
          fi

  build:
    if: ${{ !contains(github.event.release.body, 'Triggered on e-mission-server new release. Bumping up release version.') }}
    needs: [get-branch-name]
    uses: e-mission/e-mission-server/.github/workflows/reusable_image_build_push.yml@master
    with:
      repo: ${{ github.event.repository.name }}
      branch: ${{ needs.get-branch-name.outputs.branch_name }}
    secrets: inherit
